### ISSUE TITLE
how to run project without secrets.dart?

### ISSUE THREAD

**Issue by thechawla225** [StonePack/fluddit#23]
**Describe the bug**
I'm trying to run the project but the package:fluddit/secrets.dart seems to be missing and It seems I can't run the project without it. Is there any way to run without secrets.dart?

**To Reproduce**
1. Fork repo
2. run flutter pub get
3. run command flutter run

**Expected behavior**
Error in building.

**Screenshots**
![image](https://user-images.githubusercontent.com/45570514/133030374-2c7168f4-65dc-4691-a9ba-b0705131eff8.png)

**Environment:**
 - trying to run code on windows 10

**Comment by StonePack** [comment]
Hey @thechawla225, the secrets file is used to hold info that is specific to a compiled version of Fluddit. For any forks or packages built other than the official, you will have to make a new 'secrets.dart' file in the root of the 'lib' folder. You will also need to need to register for a Reddit 'Web App' here: https://www.reddit.com/prefs/apps.

Note: When registering the app, the redirect URI isn't super important but it should be something like 'https://localhost:4242'

After registering your app, note client ID displayed underneath the words 'Web App' and the client secret displayed as the 'secret' property of your newly registered app. Then you will need to generate a basic auth token, this is done by base64 encoding the text '$YOUR_CLIENT_ID:$YOUR_CLIENT_SECRET'.

Once you have those three properties you can add the following variables to your secrets.dart file:

```
String basicAuth = $YOUR_BASIC_AUTH;

String clientId = $YOUR_CLIENT_ID;

String clientSecret = $YOUR_CLIENT_SECRET;

String codeVerifier = 'someRandomString';

String redirectUri = $YOUR_REDIRECT_URI;

String userAgent = 'android:fluddit-fork';
```

Hope this helps, let me know if you have any other questions!

**Comment by StonePack** [comment]
Closing as resolved, will reopen if further clarification is needed.
